export const amharicCharacters = [
    { amharic: 'ሀ', transliteration: 'ha' },
    { amharic: 'ሁ', transliteration: 'hu' },
    { amharic: 'ሂ', transliteration: 'hi' },
    { amharic: 'ሃ', transliteration: 'hā' },
    { amharic: 'ሄ', transliteration: 'hé' },
    { amharic: 'ህ', transliteration: 'h' },
    { amharic: 'ሆ', transliteration: 'ho' },

    { amharic: 'ለ', transliteration: 'le' },
    { amharic: 'ሉ', transliteration: 'lu' },
    { amharic: 'ሊ', transliteration: 'li' },
    { amharic: 'ላ', transliteration: 'lā' },
    { amharic: 'ሌ', transliteration: 'lé' },
    { amharic: 'ል', transliteration: 'l' },
    { amharic: 'ሎ', transliteration: 'lo' },

    { amharic: 'ሐ', transliteration: 'ḥa' },
    { amharic: 'ሑ', transliteration: 'ḥu' },
    { amharic: 'ሒ', transliteration: 'ḥi' },
    { amharic: 'ሓ', transliteration: 'ḥā' },
    { amharic: 'ሔ', transliteration: 'ḥé' },
    { amharic: 'ሕ', transliteration: 'ḥ' },
    { amharic: 'ሖ', transliteration: 'ḥo' },

    { amharic: 'መ', transliteration: 'me' },
    { amharic: 'ሙ', transliteration: 'mu' },
    { amharic: 'ሚ', transliteration: 'mi' },
    { amharic: 'ማ', transliteration: 'mā' },
    { amharic: 'ሜ', transliteration: 'mé' },
    { amharic: 'ም', transliteration: 'm' },
    { amharic: 'ሞ', transliteration: 'mo' },

    { amharic: 'ሠ', transliteration: 'se' },
    { amharic: 'ሡ', transliteration: 'su' },
    { amharic: 'ሲ', transliteration: 'si' },
    { amharic: 'ሣ', transliteration: 'sā' },
    { amharic: 'ሤ', transliteration: 'sé' },
    { amharic: 'ሥ', transliteration: 's' },
    { amharic: 'ሦ', transliteration: 'so' },

    { amharic: 'ረ', transliteration: 're' },
    { amharic: 'ሩ', transliteration: 'ru' },
    { amharic: 'ሪ', transliteration: 'ri' },
    { amharic: 'ራ', transliteration: 'rā' },
    { amharic: 'ሬ', transliteration: 'ré' },
    { amharic: 'ር', transliteration: 'r' },
    { amharic: 'ሮ', transliteration: 'ro' },

    { amharic: 'ሰ', transliteration: 'se' },
    { amharic: 'ሱ', transliteration: 'su' },
    { amharic: 'ሲ', transliteration: 'si' },
    { amharic: 'ሳ', transliteration: 'sā' },
    { amharic: 'ሴ', transliteration: 'sé' },
    { amharic: 'ስ', transliteration: 's' },
    { amharic: 'ሶ', transliteration: 'so' },

    { amharic: 'ሸ', transliteration: 'she' },
    { amharic: 'ሹ', transliteration: 'shu' },
    { amharic: 'ሺ', transliteration: 'shi' },
    { amharic: 'ሻ', transliteration: 'shā' },
    { amharic: 'ሼ', transliteration: 'shé' },
    { amharic: 'ሽ', transliteration: 'sh' },
    { amharic: 'ሾ', transliteration: 'sho' },

    { amharic: 'ቀ', transliteration: 'qe' },
    { amharic: 'ቁ', transliteration: 'qu' },
    { amharic: 'ቂ', transliteration: 'qi' },
    { amharic: 'ቃ', transliteration: 'qā' },
    { amharic: 'ቄ', transliteration: 'qé' },
    { amharic: 'ቅ', transliteration: 'q' },
    { amharic: 'ቆ', transliteration: 'qo' },

    { amharic: 'በ', transliteration: 'be' },
    { amharic: 'ቡ', transliteration: 'bu' },
    { amharic: 'ቢ', transliteration: 'bi' },
    { amharic: 'ባ', transliteration: 'bā' },
    { amharic: 'ቤ', transliteration: 'bé' },
    { amharic: 'ብ', transliteration: 'b' },
    { amharic: 'ቦ', transliteration: 'bo' },

    { amharic: 'ተ', transliteration: 'te' },
    { amharic: 'ቱ', transliteration: 'tu' },
    { amharic: 'ቲ', transliteration: 'ti' },
    { amharic: 'ታ', transliteration: 'tā' },
    { amharic: 'ቴ', transliteration: 'té' },
    { amharic: 'ት', transliteration: 't' },
    { amharic: 'ቶ', transliteration: 'to' },

    { amharic: 'ቸ', transliteration: 'che' },
    { amharic: 'ቹ', transliteration: 'chu' },
    { amharic: 'ቺ', transliteration: 'chi' },
    { amharic: 'ቻ', transliteration: 'chā' },
    { amharic: 'ቼ', transliteration: 'ché' },
    { amharic: 'ች', transliteration: 'ch' },
    { amharic: 'ቾ', transliteration: 'cho' },

    { amharic: 'ኀ', transliteration: 'ha' },
    { amharic: 'ኁ', transliteration: 'hu' },
    { amharic: 'ኂ', transliteration: 'hi' },
    { amharic: 'ኃ', transliteration: 'hā' },
    { amharic: 'ኄ', transliteration: 'hé' },
    { amharic: 'ኅ', transliteration: 'h' },
    { amharic: 'ኆ', transliteration: 'ho' },

    { amharic: 'ነ', transliteration: 'ne' },
    { amharic: 'ኑ', transliteration: 'nu' },
    { amharic: 'ኒ', transliteration: 'ni' },
    { amharic: 'ና', transliteration: 'nā' },
    { amharic: 'ኔ', transliteration: 'né' },
    { amharic: 'ን', transliteration: 'n' },
    { amharic: 'ኖ', transliteration: 'no' },

    { amharic: 'ኘ', transliteration: 'nye' },
    { amharic: 'ኙ', transliteration: 'nyu' },
    { amharic: 'ኚ', transliteration: 'nyi' },
    { amharic: 'ኛ', transliteration: 'nyā' },
    { amharic: 'ኜ', transliteration: 'nyé' },
    { amharic: 'ኝ', transliteration: 'ny' },
    { amharic: 'ኞ', transliteration: 'nyo' },

    { amharic: 'አ', transliteration: 'a' },
    { amharic: 'ኡ', transliteration: 'u' },
    { amharic: 'ኢ', transliteration: 'i' },
    { amharic: 'ኣ', transliteration: 'ā' },
    { amharic: 'ኤ', transliteration: 'ē' },
    { amharic: 'እ', transliteration: 'e' },
    { amharic: 'ኦ', transliteration: 'o' },

    { amharic: 'ከ', transliteration: 'ke' },
    { amharic: 'ኩ', transliteration: 'ku' },
    { amharic: 'ኪ', transliteration: 'ki' },
    { amharic: 'ካ', transliteration: 'kā' },
    { amharic: 'ኬ', transliteration: 'ké' },
    { amharic: 'ክ', transliteration: 'k' },
    { amharic: 'ኮ', transliteration: 'ko' },

    { amharic: 'ኸ', transliteration: 'kh' },
    { amharic: 'ኹ', transliteration: 'khu' },
    { amharic: 'ኺ', transliteration: 'khi' },
    { amharic: 'ኻ', transliteration: 'khā' },
    { amharic: 'ኼ', transliteration: 'khé' },
    { amharic: 'ኽ', transliteration: 'kh' },
    { amharic: 'ኾ', transliteration: 'kho' },

    { amharic: 'ወ', transliteration: 'we' },
    { amharic: 'ዉ', transliteration: 'wu' },
    { amharic: 'ዊ', transliteration: 'wi' },
    { amharic: 'ዋ', transliteration: 'wā' },
    { amharic: 'ዌ', transliteration: 'wé' },
    { amharic: 'ው', transliteration: 'w' },
    { amharic: 'ዎ', transliteration: 'wo' },

    { amharic: 'ዐ', transliteration: 'a' },
    { amharic: 'ዑ', transliteration: 'u' },
    { amharic: 'ዒ', transliteration: 'i' },
    { amharic: 'ዓ', transliteration: 'ā' },
    { amharic: 'ዔ', transliteration: 'ē' },
    { amharic: 'ዕ', transliteration: 'e' },
    { amharic: 'ዖ', transliteration: 'o' },

    { amharic: 'ዘ', transliteration: 'ze' },
    { amharic: 'ዙ', transliteration: 'zu' },
    { amharic: 'ዚ', transliteration: 'zi' },
    { amharic: 'ዛ', transliteration: 'zā' },
    { amharic: 'ዜ', transliteration: 'zé' },
    { amharic: 'ዝ', transliteration: 'z' },
    { amharic: 'ዞ', transliteration: 'zo' },

    { amharic: 'ዠ', transliteration: 'zhe' },
    { amharic: 'ዡ', transliteration: 'zhu' },
    { amharic: 'ዢ', transliteration: 'zhi' },
    { amharic: 'ዣ', transliteration: 'zhā' },
    { amharic: 'ዤ', transliteration: 'zhé' },
    { amharic: 'ዥ', transliteration: 'zh' },
    { amharic: 'ዦ', transliteration: 'zho' },

    { amharic: 'የ', transliteration: 'ye' },
    { amharic: 'ዩ', transliteration: 'yu' },
    { amharic: 'ዪ', transliteration: 'yi' },
    { amharic: 'ያ', transliteration: 'yā' },
    { amharic: 'ዬ', transliteration: 'yé' },
    { amharic: 'ይ', transliteration: 'y' },
    { amharic: 'ዮ', transliteration: 'yo' },

    { amharic: 'ደ', transliteration: 'de' },
    { amharic: 'ዱ', transliteration: 'du' },
    { amharic: 'ዲ', transliteration: 'di' },
    { amharic: 'ዳ', transliteration: 'dā' },
    { amharic: 'ዴ', transliteration: 'dé' },
    { amharic: 'ድ', transliteration: 'd' },
    { amharic: 'ዶ', transliteration: 'do' },

    { amharic: 'ጀ', transliteration: 'je' },
    { amharic: 'ጁ', transliteration: 'ju' },
    { amharic: 'ጂ', transliteration: 'ji' },
    { amharic: 'ጃ', transliteration: 'jā' },
    { amharic: 'ጄ', transliteration: 'jé' },
    { amharic: 'ጅ', transliteration: 'j' },
    { amharic: 'ጆ', transliteration: 'jo' },

    { amharic: 'ገ', transliteration: 'ge' },
    { amharic: 'ጉ', transliteration: 'gu' },
    { amharic: 'ጊ', transliteration: 'gi' },
    { amharic: 'ጋ', transliteration: 'gā' },
    { amharic: 'ጌ', transliteration: 'gé' },
    { amharic: 'ግ', transliteration: 'g' },
    { amharic: 'ጎ', transliteration: 'go' },

    { amharic: 'ጠ', transliteration: 'ṭe' },
    { amharic: 'ጡ', transliteration: 'ṭu' },
    { amharic: 'ጢ', transliteration: 'ṭi' },
    { amharic: 'ጣ', transliteration: 'ṭā' },
    { amharic: 'ጤ', transliteration: 'ṭé' },
    { amharic: 'ጥ', transliteration: 'ṭ' },
    { amharic: 'ጦ', transliteration: 'ṭo' },

    { amharic: 'ጨ', transliteration: 'che' },
    { amharic: 'ጩ', transliteration: 'chu' },
    { amharic: 'ጪ', transliteration: 'chi' },
    { amharic: 'ጫ', transliteration: 'chā' },
    { amharic: 'ጬ', transliteration: 'ché' },
    { amharic: 'ጭ', transliteration: 'ch' },
    { amharic: 'ጮ', transliteration: 'cho' },

    { amharic: 'ጰ', transliteration: 'pe' },
    { amharic: 'ጱ', transliteration: 'pu' },
    { amharic: 'ጲ', transliteration: 'pi' },
    { amharic: 'ጳ', transliteration: 'pā' },
    { amharic: 'ጴ', transliteration: 'pé' },
    { amharic: 'ጵ', transliteration: 'p' },
    { amharic: 'ጶ', transliteration: 'po' },

    { amharic: 'ጸ', transliteration: 'tse' },
    { amharic: 'ጹ', transliteration: 'tsu' },
    { amharic: 'ጺ', transliteration: 'tsi' },
    { amharic: 'ጻ', transliteration: 'tsā' },
    { amharic: 'ጼ', transliteration: 'tsé' },
    { amharic: 'ጽ', transliteration: 'ts' },
    { amharic: 'ጾ', transliteration: 'tso' },

    { amharic: 'ፀ', transliteration: 'tse' },
    { amharic: 'ፁ', transliteration: 'tsu' },
    { amharic: 'ፂ', transliteration: 'tsi' },
    { amharic: 'ፃ', transliteration: 'tsā' },
    { amharic: 'ፄ', transliteration: 'tsé' },
    { amharic: 'ፅ', transliteration: 'ts' },
    { amharic: 'ፆ', transliteration: 'tso' },

    { amharic: 'ፈ', transliteration: 'fe' },
    { amharic: 'ፉ', transliteration: 'fu' },
    { amharic: 'ፊ', transliteration: 'fi' },
    { amharic: 'ፋ', transliteration: 'fā' },
    { amharic: 'ፌ', transliteration: 'fé' },
    { amharic: 'ፍ', transliteration: 'f' },
    { amharic: 'ፎ', transliteration: 'fo' },

    { amharic: 'ፐ', transliteration: 'pe' },
    { amharic: 'ፑ', transliteration: 'pu' },
    { amharic: 'ፒ', transliteration: 'pi' },
    { amharic: 'ፓ', transliteration: 'pā' },
    { amharic: 'ፔ', transliteration: 'pé' },
    { amharic: 'ፕ', transliteration: 'p' },
    { amharic: 'ፖ', transliteration: 'po' },
];